name: "Skenario 1 - Level 2 - Deploy Node.js (systemd)"

on:
  push:
    branches: [ main ]
    paths:
      - 'skenario1-github-actions-vps-proxycommand/level2-nodejs-systemd/app/**'

  workflow_dispatch:
    inputs:
      restart_only:
        description: 'Hanya restart service tanpa upload ulang file?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy Node.js app ke WSL
    runs-on: ubuntu-latest

    steps:

      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Install cloudflared & sshpass
        run: |
          curl -L \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb \
            -o cloudflared.deb

          sudo dpkg -i cloudflared.deb

          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Siapkan SSH config
        env:
          CF_ACCESS_HOSTNAME: ${{ secrets.CF_ACCESS_HOSTNAME }}
        run: |
          mkdir -p ~/.ssh

          cat >> ~/.ssh/config <<EOC
          Host vm-a
            HostName ${CF_ACCESS_HOSTNAME}
            User ${{ secrets.VPS_USERNAME }}
            ProxyCommand cloudflared access ssh --hostname %h
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOC

      - name: Deploy aplikasi
        if: ${{ github.event.inputs.restart_only != 'true' }}
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |

          echo "=== Cek Node.js ==="

          sshpass -e ssh vm-a "
            node --version
          "

          echo "=== Buat directory aplikasi ==="

          sshpass -e ssh vm-a \
            "sudo mkdir -p /opt/level2-node"

          echo "=== Upload aplikasi ==="

          sshpass -e scp -o StrictHostKeyChecking=no \
            skenario1-github-actions-vps-proxycommand/level2-nodejs-systemd/app/server.js \
            skenario1-github-actions-vps-proxycommand/level2-nodejs-systemd/app/package.json \
            vm-a:/tmp/

          echo "=== Pasang aplikasi ==="

          sshpass -e ssh vm-a "
            sudo cp /tmp/server.js /opt/level2-node/server.js &&
            sudo cp /tmp/package.json /opt/level2-node/package.json &&
            sudo chown -R fendy:fendy /opt/level2-node &&
            cd /opt/level2-node &&
            npm install --omit=dev
          "

      - name: Restart Node.js service
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |

          echo "=== Restart level2-node ==="

          sshpass -e ssh vm-a \
            "sudo systemctl restart level2-node"

          echo "=== Status service ==="

          sshpass -e ssh vm-a \
            "sudo systemctl status level2-node --no-pager"
