name: "Skenario 1 - Level 3 - Deploy Flask (release + cron)"

on:
  push:
    tags:
      - 'v*'

  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy:
    name: Deploy Flask app ke WSL
    runs-on: ubuntu-latest

    steps:

      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Tentukan versi rilis
        id: ver
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "version=scheduled-refresh" >> "$GITHUB_OUTPUT"
          fi

      - name: Install cloudflared & sshpass
        run: |
          curl -L \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb \
            -o cloudflared.deb

          sudo dpkg -i cloudflared.deb

          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Siapkan SSH config
        env:
          CF_ACCESS_HOSTNAME: ${{ secrets.CF_ACCESS_HOSTNAME }}
        run: |
          mkdir -p ~/.ssh

          cat >> ~/.ssh/config <<EOC
          Host vm-a
            HostName ${CF_ACCESS_HOSTNAME}
            User ${{ secrets.VPS_USERNAME }}
            ProxyCommand cloudflared access ssh --hostname %h
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOC

      - name: Upload kode Flask
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |
          echo "=== Upload Flask ==="

          sshpass -e scp -o StrictHostKeyChecking=no \
            skenario1-github-actions-vps-proxycommand/level3-python-flask-release/app/app.py \
            skenario1-github-actions-vps-proxycommand/level3-python-flask-release/app/requirements.txt \
            vm-a:/tmp/

          sshpass -e ssh vm-a "
            sudo cp /tmp/app.py /opt/level3-flask/app.py &&
            sudo cp /tmp/requirements.txt /opt/level3-flask/requirements.txt &&
            sudo chown -R fendy:fendy /opt/level3-flask
          "

      - name: Install dependency & update version
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
          RELEASE_VERSION: ${{ steps.ver.outputs.version }}
        run: |
          echo "=== Install dependency ==="

          sshpass -e ssh vm-a "
            /opt/level3-flask/venv/bin/pip install -r /opt/level3-flask/requirements.txt
          "

          echo "=== Update APP_VERSION ==="

          sshpass -e ssh vm-a "
            sudo sed -i 's/^Environment=APP_VERSION=.*/Environment=APP_VERSION=${RELEASE_VERSION}/' /etc/systemd/system/level3-flask.service &&
            sudo systemctl daemon-reload &&
            sudo systemctl restart level3-flask
          "

      - name: Cek status service
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -e ssh vm-a \
            "sudo systemctl status level3-flask --no-pager"
